### ISSUE TITLE
Problems with executed Python Plot

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/knime-scripting#57] opened 2014-12-22 13:22 UTC
First, I got this error message when I wanted to view an executed Python Plot (workflow was saved and closed in-between):
ERROR    Python Plot                     View instantiation failed: null

Then I see the message "Error: directory on output file does not exist" when I open the dialog (I think when I opened the workflow then the volume was not mounted yet. Now it is mounted, but when I open the dialog is still displays the same message)

Last, if re-execute the Plot I get this message:
ERROR    Python Plot                     Execute failed: Image file '/Volumes/tds/projects/Tau_Secretion_Bonn/screen_analysis/KNIMEplots/Venn_uncorrectedVsCorrectedVsCorrectedThr0.45_100perc_propo_141216.png' already exists, enable overwrite to replace it

...which is correct because the file indeed already exists. Here, option to re-execute Plot with output .png without forcing the user to delete the path would be nice (same issue already reported for R-plot).

Martin

**Comment by stoeter** [comment] 2014-12-22 13:27
comment: indeed I re-produced it, when workflow is saved, closed and reopened the Python plots cannot be viewed anymore!

**Comment by niederle** [comment] 2015-01-05 10:16
Duplicate of issue #15

**Closed as completed by niederle** 2015-01-05 10:16 UTC
